### ISSUE TITLE
We're looking for duplicates _in_ the titles

### ISSUE THREAD

**Issue by aleksd-dfds** [priyankapandey13/hyf-homework#12]
https://github.com/priyankapandey13/hyf-homework/blob/18ebb6b87a9f316937b844547ffa65bfbdec01c1/javascript/javascript2/week2/mainscript.js#L21

What you're doing here seems to be looking for duplicates _across_ titles (are there any words found in both titles `i` and `j`?) The task i believe is to find titles which have duplicates within them ("blah blah" or "Star wars wars").

**Comment by priyankapandey13** [comment]
I have now changed it and updated it to what we supposed to do in homework now. I kind of modified it before sorry.

**Comment by aleksd-dfds** [comment]
where?

**Comment by priyankapandey13** [comment]
i accidentally put it in master many days ago and updated it there. Everybody in my class was saying that mentors are busy these day's and Danial told me that anybody from my class can review my homework so i asked my classmate mekdes to review mine. She said everything is working just need to clean the comments. Sorry i didn't want to bother u that's why did not contacted u.... 😬
